/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	virtualprivatenetworkconnectv1 "github.com/ovn-org/ovn-kubernetes/go-controller/pkg/crd/virtualprivatenetworkconnect/v1"
	applyconfigurationvirtualprivatenetworkconnectv1 "github.com/ovn-org/ovn-kubernetes/go-controller/pkg/crd/virtualprivatenetworkconnect/v1/apis/applyconfiguration/virtualprivatenetworkconnect/v1"
	scheme "github.com/ovn-org/ovn-kubernetes/go-controller/pkg/crd/virtualprivatenetworkconnect/v1/apis/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// VirtualPrivateNetworkConnectsGetter has a method to return a VirtualPrivateNetworkConnectInterface.
// A group's client should implement this interface.
type VirtualPrivateNetworkConnectsGetter interface {
	VirtualPrivateNetworkConnects() VirtualPrivateNetworkConnectInterface
}

// VirtualPrivateNetworkConnectInterface has methods to work with VirtualPrivateNetworkConnect resources.
type VirtualPrivateNetworkConnectInterface interface {
	Create(ctx context.Context, virtualPrivateNetworkConnect *virtualprivatenetworkconnectv1.VirtualPrivateNetworkConnect, opts metav1.CreateOptions) (*virtualprivatenetworkconnectv1.VirtualPrivateNetworkConnect, error)
	Update(ctx context.Context, virtualPrivateNetworkConnect *virtualprivatenetworkconnectv1.VirtualPrivateNetworkConnect, opts metav1.UpdateOptions) (*virtualprivatenetworkconnectv1.VirtualPrivateNetworkConnect, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, virtualPrivateNetworkConnect *virtualprivatenetworkconnectv1.VirtualPrivateNetworkConnect, opts metav1.UpdateOptions) (*virtualprivatenetworkconnectv1.VirtualPrivateNetworkConnect, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*virtualprivatenetworkconnectv1.VirtualPrivateNetworkConnect, error)
	List(ctx context.Context, opts metav1.ListOptions) (*virtualprivatenetworkconnectv1.VirtualPrivateNetworkConnectList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *virtualprivatenetworkconnectv1.VirtualPrivateNetworkConnect, err error)
	Apply(ctx context.Context, virtualPrivateNetworkConnect *applyconfigurationvirtualprivatenetworkconnectv1.VirtualPrivateNetworkConnectApplyConfiguration, opts metav1.ApplyOptions) (result *virtualprivatenetworkconnectv1.VirtualPrivateNetworkConnect, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, virtualPrivateNetworkConnect *applyconfigurationvirtualprivatenetworkconnectv1.VirtualPrivateNetworkConnectApplyConfiguration, opts metav1.ApplyOptions) (result *virtualprivatenetworkconnectv1.VirtualPrivateNetworkConnect, err error)
	VirtualPrivateNetworkConnectExpansion
}

// virtualPrivateNetworkConnects implements VirtualPrivateNetworkConnectInterface
type virtualPrivateNetworkConnects struct {
	*gentype.ClientWithListAndApply[*virtualprivatenetworkconnectv1.VirtualPrivateNetworkConnect, *virtualprivatenetworkconnectv1.VirtualPrivateNetworkConnectList, *applyconfigurationvirtualprivatenetworkconnectv1.VirtualPrivateNetworkConnectApplyConfiguration]
}

// newVirtualPrivateNetworkConnects returns a VirtualPrivateNetworkConnects
func newVirtualPrivateNetworkConnects(c *K8sV1Client) *virtualPrivateNetworkConnects {
	return &virtualPrivateNetworkConnects{
		gentype.NewClientWithListAndApply[*virtualprivatenetworkconnectv1.VirtualPrivateNetworkConnect, *virtualprivatenetworkconnectv1.VirtualPrivateNetworkConnectList, *applyconfigurationvirtualprivatenetworkconnectv1.VirtualPrivateNetworkConnectApplyConfiguration](
			"virtualprivatenetworkconnects",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *virtualprivatenetworkconnectv1.VirtualPrivateNetworkConnect {
				return &virtualprivatenetworkconnectv1.VirtualPrivateNetworkConnect{}
			},
			func() *virtualprivatenetworkconnectv1.VirtualPrivateNetworkConnectList {
				return &virtualprivatenetworkconnectv1.VirtualPrivateNetworkConnectList{}
			},
		),
	}
}
