//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// SPDX-FileCopyrightText: Copyright The OVN-Kubernetes Contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by openapi-gen. DO NOT EDIT.

package v1alpha1

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in FeatureConfig) OpenAPIModelName() string {
	return "com.github.ovn-kubernetes.ovn-kubernetes.go-controller.pkg.crd.observabilityconfigs.v1alpha1.FeatureConfig"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in Filter) OpenAPIModelName() string {
	return "com.github.ovn-kubernetes.ovn-kubernetes.go-controller.pkg.crd.observabilityconfigs.v1alpha1.Filter"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ObservabilityConfig) OpenAPIModelName() string {
	return "com.github.ovn-kubernetes.ovn-kubernetes.go-controller.pkg.crd.observabilityconfigs.v1alpha1.ObservabilityConfig"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ObservabilityConfigList) OpenAPIModelName() string {
	return "com.github.ovn-kubernetes.ovn-kubernetes.go-controller.pkg.crd.observabilityconfigs.v1alpha1.ObservabilityConfigList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ObservabilitySpec) OpenAPIModelName() string {
	return "com.github.ovn-kubernetes.ovn-kubernetes.go-controller.pkg.crd.observabilityconfigs.v1alpha1.ObservabilitySpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ObservabilityStatus) OpenAPIModelName() string {
	return "com.github.ovn-kubernetes.ovn-kubernetes.go-controller.pkg.crd.observabilityconfigs.v1alpha1.ObservabilityStatus"
}
