processor:
  ignoreTypes:
    - "(EgressIP|EgressQoS|EgressFirewall|EgressService|AdminPolicyBasedExternalRoute|ObservabilityConfig)List$"
  ignoreFields:
    - "TypeMeta$"

render:
  kubernetesVersion: 1.28
