---
# DPU Template - Production 6-Container OVN Stack (Bottom Half)
# Based on production dpu.yaml with full OVN infrastructure
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: ovnkube-node-dpu
  namespace: ovn-kubernetes
  annotations:
    kubernetes.io/description: |
      This DaemonSet launches the full ovn-kubernetes OVN stack for DPU nodes.
spec:
  selector:
    matchLabels:
      app: ovnkube-node-dpu
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ovnkube-node-dpu
        name: ovnkube-node-dpu
        component: network
        type: infra
        kubernetes.io/os: "linux"
    spec:
      priorityClassName: "system-cluster-critical"
      serviceAccountName: ovnkube-node
      hostNetwork: true
      dnsPolicy: Default
      hostPID: true
      containers:

      # Container 1: NB OVSDB
      - name: nb-ovsdb
        image: "localhost/ovn-daemonset-fedora:dev"
        imagePullPolicy: "IfNotPresent"
        command: ["/root/ovnkube.sh", "local-nb-ovsdb"]
        securityContext:
          runAsUser: 0
          capabilities:
            add: ["NET_ADMIN"]
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
        - mountPath: /etc/openvswitch/
          name: host-etc-ovs
        - mountPath: /etc/ovn/
          name: host-var-lib-ovs
        - mountPath: /var/log/openvswitch/
          name: host-var-log-ovs
        - mountPath: /var/log/ovn/
          name: host-var-log-ovs
        - mountPath: /ovn-cert
          name: host-ovn-cert
          readOnly: true
        - mountPath: /var/run/ovn/
          name: host-var-run-ovs
        - mountPath: /var/run/openvswitch/
          name: host-var-run-ovs
        resources:
          requests:
            cpu: 100m
            memory: 300Mi
        env:
        - name: OVN_DAEMONSET_VERSION
          value: "1.2.0"
        - name: OVN_LOGLEVEL_NB
          value: "-vconsole:info -vfile:info"
        - name: K8S_APISERVER
          valueFrom:
            configMapKeyRef:
              name: ovn-config
              key: k8s_apiserver
        - name: OVN_KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: K8S_NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: K8S_NODE
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        readinessProbe:
          exec:
            command: ["/usr/bin/ovn-kube-util", "readiness-probe", "-t", "ovnnb-db"]
          initialDelaySeconds: 30
          periodSeconds: 60
          timeoutSeconds: 30

      # Container 2: SB OVSDB
      - name: sb-ovsdb
        image: "localhost/ovn-daemonset-fedora:dev"
        imagePullPolicy: "IfNotPresent"
        command: ["/root/ovnkube.sh", "local-sb-ovsdb"]
        securityContext:
          runAsUser: 0
          capabilities:
            add: ["NET_ADMIN"]
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
        - mountPath: /etc/openvswitch/
          name: host-etc-ovs
        - mountPath: /etc/ovn/
          name: host-var-lib-ovs
        - mountPath: /var/log/openvswitch/
          name: host-var-log-ovs
        - mountPath: /var/log/ovn/
          name: host-var-log-ovs
        - mountPath: /ovn-cert
          name: host-ovn-cert
          readOnly: true
        - mountPath: /var/run/ovn/
          name: host-var-run-ovs
        - mountPath: /var/run/openvswitch/
          name: host-var-run-ovs
        resources:
          requests:
            cpu: 100m
            memory: 300Mi
        env:
        - name: OVN_DAEMONSET_VERSION
          value: "1.2.0"
        - name: OVN_LOGLEVEL_SB
          value: "-vconsole:info -vfile:info"
        - name: K8S_APISERVER
          valueFrom:
            configMapKeyRef:
              name: ovn-config
              key: k8s_apiserver
        - name: OVN_KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: K8S_NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: K8S_NODE
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: OVN_SSL_ENABLE
          value: "no"
        readinessProbe:
          exec:
            command: ["/usr/bin/ovn-kube-util", "readiness-probe", "-t", "ovnsb-db"]
          initialDelaySeconds: 30
          periodSeconds: 60
          timeoutSeconds: 30

      # Container 3: OVN Northd
      - name: ovn-northd
        image: "localhost/ovn-daemonset-fedora:dev"
        imagePullPolicy: "IfNotPresent"
        command: ["/root/ovnkube.sh", "run-ovn-northd"]
        securityContext:
          runAsUser: 0
          capabilities:
            add: ["SYS_NICE"]
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
        - mountPath: /var/run/dbus/
          name: host-var-run-dbus
          readOnly: true
        - mountPath: /var/log/openvswitch/
          name: host-var-log-ovs
        - mountPath: /var/log/ovn/
          name: host-var-log-ovs
        - mountPath: /var/run/openvswitch/
          name: host-var-run-ovs
        - mountPath: /var/run/ovn/
          name: host-var-run-ovs
        - mountPath: /ovn-cert
          name: host-ovn-cert
          readOnly: true
        resources:
          requests:
            cpu: 100m
            memory: 300Mi
        env:
        - name: OVN_DAEMONSET_VERSION
          value: "1.2.0"
        - name: OVN_LOGLEVEL_NORTHD
          value: "-vconsole:info -vfile:info"
        - name: K8S_APISERVER
          valueFrom:
            configMapKeyRef:
              name: ovn-config
              key: k8s_apiserver
        - name: OVN_KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: OVN_SSL_ENABLE
          value: "no"
        - name: OVN_NORTH
          value: "local"
        - name: OVN_SOUTH
          value: "local"
        readinessProbe:
          exec:
            command: ["/usr/bin/ovn-kube-util", "readiness-probe", "-t", "ovn-northd"]
          initialDelaySeconds: 30
          periodSeconds: 60
          timeoutSeconds: 30

      # Container 4: OVNKube Controller with Node (Main Controller)
      - name: ovnkube-controller-with-node
        image: "localhost/ovn-daemonset-fedora:dev"
        imagePullPolicy: "IfNotPresent"
        command: ["/root/ovnkube.sh", "ovnkube-controller-with-node"]
        securityContext:
          runAsUser: 0
          privileged: true
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
        - mountPath: /host
          name: host-slash
          readOnly: true
        - mountPath: /var/lib/kubelet
          name: host-kubelet
          readOnly: true
        - mountPath: /var/run/dbus/
          name: host-var-run-dbus
          readOnly: true
        - mountPath: /var/log/ovn-kubernetes/
          name: host-var-log-ovnkube
        - mountPath: /var/run/ovn-kubernetes
          name: host-var-run-ovn-kubernetes
        - mountPath: /opt/cni/bin
          name: host-opt-cni-bin
        - mountPath: /etc/cni/net.d
          name: host-etc-cni-netd
        - mountPath: /var/run/netns
          name: host-netns
          mountPropagation: Bidirectional
        - mountPath: /var/run/openvswitch/
          name: host-var-run-ovs
        - mountPath: /var/run/ovn/
          name: host-var-run-ovs
        - mountPath: /ovn-cert
          name: host-ovn-cert
          readOnly: true
        - mountPath: /etc/openvswitch/
          name: host-etc-ovs
        - mountPath: /etc/ovn/
          name: host-var-lib-ovs
          readOnly: true
        resources:
          requests:
            cpu: 100m
            memory: 300Mi
        env:
        - name: OVN_DAEMONSET_VERSION
          value: "1.2.0"
        - name: OVNKUBE_LOGLEVEL
          value: "4"
        - name: OVNKUBE_LOGFILE_MAXSIZE
          value: "100"
        - name: OVNKUBE_LOGFILE_MAXBACKUPS
          value: "5"
        - name: OVNKUBE_LOGFILE_MAXAGE
          value: "5"
        - name: OVN_NET_CIDR
          valueFrom:
            configMapKeyRef:
              name: ovn-config
              key: net_cidr
        - name: OVN_SVC_CIDR
          valueFrom:
            configMapKeyRef:
              name: ovn-config
              key: svc_cidr
        - name: K8S_APISERVER
          valueFrom:
            configMapKeyRef:
              name: ovn-config
              key: k8s_apiserver
        - name: OVN_MTU
          valueFrom:
            configMapKeyRef:
              name: ovn-config
              key: mtu
        - name: OVN_ROUTABLE_MTU
          valueFrom:
            configMapKeyRef:
              name: ovn-config
              key: routable_mtu
              optional: true
        - name: K8S_NODE
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: K8S_NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: OVN_KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: OVN_GATEWAY_MODE
          value: "shared"
        # REMOVED: OVN_GATEWAY_OPTS - now using automatic gateway interface detection via DPU provider
        # The GetDPUHostInterface() function will auto-detect rep0-0 via VethRepresentorProvider
        - name: OVN_ADMIN_NETWORK_POLICY_ENABLE
          value: "true"
        - name: OVN_EGRESSIP_ENABLE
          value: "false"
        - name: OVN_EGRESSIP_HEALTHCHECK_PORT
          value: "9107"
        - name: OVN_EGRESSFIREWALL_ENABLE
          value: "false"
        - name: OVN_EGRESSQOS_ENABLE
          value: "false"
        - name: OVN_NETWORK_QOS_ENABLE
          value: "true"
        - name: OVN_ENCAP_PORT
          value: "6081"
        - name: OVN_V4_JOIN_SUBNET
          value: "100.64.0.0/16"
        - name: OVN_V6_JOIN_SUBNET
          value: "fd98::/64"
        - name: OVN_V4_MASQUERADE_SUBNET
          value: "169.254.0.0/17"
        - name: OVN_V6_MASQUERADE_SUBNET
          value: "fd69::/112"
        - name: OVN_MULTICAST_ENABLE
          value: "true"
        - name: OVN_UNPRIVILEGED_MODE
          value: "no"
        - name: OVN_SSL_ENABLE
          value: "no"
        - name: OVN_DISABLE_OVN_IFACE_ID_VER
          value: "false"
        - name: OVN_REMOTE_PROBE_INTERVAL
          value: "100000"
        - name: OVN_ENABLE_LFLOW_CACHE
          value: "false"
        - name: OVN_MULTI_NETWORK_ENABLE
          value: "false"
        - name: OVN_ACL_LOGGING_RATE_LIMIT
          value: "20"
        - name: OVN_STATELESS_NETPOL_ENABLE
          value: "true"
        - name: OVN_HOST_NETWORK_NAMESPACE
          valueFrom:
            configMapKeyRef:
              name: ovn-config
              key: host_network_namespace
        - name: OVN_NORTH
          value: "local"
        - name: OVN_SOUTH
          value: "local"
        - name: OVN_ENABLE_INTERCONNECT
          value: "true"
        - name: OVN_ENABLE_MULTI_EXTERNAL_GATEWAY
          value: "false"
        - name: OVN_ENABLE_OVNKUBE_IDENTITY
          value: "false"
        - name: OVN_DISABLE_REQUESTEDCHASSIS
          value: "true"
        - name: OVN_ENABLE_SVC_TEMPLATE_SUPPORT
          value: "false"
        - name: OVN_ENABLE_DNSNAMERESOLVER
          value: "false"
        - name: OVN_NOHOSTSUBNET_LABEL
          value: "k8s.ovn.org/ovn-managed=false"
        # CRITICAL: DPU mode environment variable
        - name: OVNKUBE_NODE_MODE
          value: "dpu"
        # DPU provider for VethRepresentorProvider
        - name: OVNKUBE_DPU_PROVIDER
          value: "veth"
        - name: OVNKUBE_NODE_LEASE_NAMESPACE
          value: "ovn-kubernetes"
        # CRITICAL: OVN encapsulation IP required for DPU mode
        - name: OVN_ENCAP_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        readinessProbe:
          httpGet:
            path: /metrics
            port: 9476
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5

      # Container 5: OVN Controller
      - name: ovn-controller
        image: "localhost/ovn-daemonset-fedora:dev"
        imagePullPolicy: "IfNotPresent"
        command: ["/root/ovnkube.sh", "ovn-controller"]
        securityContext:
          runAsUser: 0
          capabilities:
            add: ["SYS_NICE"]
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
        - mountPath: /var/run/dbus/
          name: host-var-run-dbus
          readOnly: true
        - mountPath: /var/log/openvswitch/
          name: host-var-log-ovs
        - mountPath: /var/log/ovn/
          name: host-var-log-ovs
        - mountPath: /var/run/openvswitch/
          name: host-var-run-ovs
        - mountPath: /var/run/ovn/
          name: host-var-run-ovs
        - mountPath: /ovn-cert
          name: host-ovn-cert
          readOnly: true
        resources:
          requests:
            cpu: 100m
            memory: 300Mi
        env:
        - name: OVN_DAEMONSET_VERSION
          value: "1.2.0"
        - name: OVN_LOGLEVEL_CONTROLLER
          value: "-vconsole:info"
        - name: K8S_APISERVER
          valueFrom:
            configMapKeyRef:
              name: ovn-config
              key: k8s_apiserver
        - name: OVN_KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: OVN_SSL_ENABLE
          value: ""
        - name: OVN_NORTH
          value: "local"
        - name: OVN_SOUTH
          value: "local"
        readinessProbe:
          exec:
            command: ["/usr/bin/ovn-kube-util", "readiness-probe", "-t", "ovn-controller"]
          initialDelaySeconds: 30
          periodSeconds: 60
          timeoutSeconds: 30

      # Container 6: OVS Metrics Exporter
      - name: ovs-metrics-exporter
        image: "localhost/ovn-daemonset-fedora:dev"
        imagePullPolicy: "IfNotPresent"
        command: ["/root/ovnkube.sh", "ovs-metrics"]
        securityContext:
          runAsUser: 0
          capabilities:
            add: ["NET_ADMIN"]
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
        - mountPath: /var/run/dbus/
          name: host-var-run-dbus
          readOnly: true
        - mountPath: /var/log/openvswitch/
          name: host-var-log-ovs
        - mountPath: /var/run/openvswitch/
          name: host-var-run-ovs
        resources:
          requests:
            cpu: 100m
            memory: 300Mi
        env:
        - name: OVN_DAEMONSET_VERSION
          value: "1.2.0"
        - name: K8S_NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP

      # Target DPU nodes only
      nodeSelector:
        kubernetes.io/os: "linux"
        k8s.ovn.org/dpu: ""
      volumes:
      # Common volumes
      - name: host-var-run-dbus
        hostPath:
          path: /var/run/dbus
      - name: host-kubelet
        hostPath:
          path: /var/lib/kubelet
      - name: host-var-log-ovnkube
        hostPath:
          path: /var/log/ovn-kubernetes
      - name: host-var-run-ovn-kubernetes
        hostPath:
          path: /var/run/ovn-kubernetes
      - name: host-opt-cni-bin
        hostPath:
          path: /opt/cni/bin
      - name: host-etc-cni-netd
        hostPath:
          path: /etc/cni/net.d
      - name: host-slash
        hostPath:
          path: /
      - name: host-netns
        hostPath:
          path: /var/run/netns
      # OVS/OVN volumes (required for DPU nodes)
      - name: host-var-log-ovs
        hostPath:
          path: /var/log/openvswitch
      - name: host-var-run-ovs
        hostPath:
          path: /var/run/openvswitch
      - name: host-ovn-cert
        hostPath:
          path: /etc/ovn
          type: DirectoryOrCreate
      - name: host-var-lib-ovs
        hostPath:
          path: /var/lib/openvswitch
      - name: host-etc-ovs
        hostPath:
          path: /etc/openvswitch

      tolerations:
      - operator: "Exists"