// SPDX-FileCopyrightText: Copyright The OVN-Kubernetes Contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/crd/observabilityconfig/v1alpha1"
	observabilityconfigv1alpha1 "github.com/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/crd/observabilityconfig/v1alpha1/apis/applyconfiguration/observabilityconfig/v1alpha1"
	typedobservabilityconfigv1alpha1 "github.com/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/crd/observabilityconfig/v1alpha1/apis/clientset/versioned/typed/observabilityconfig/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeObservabilityConfigs implements ObservabilityConfigInterface
type fakeObservabilityConfigs struct {
	*gentype.FakeClientWithListAndApply[*v1alpha1.ObservabilityConfig, *v1alpha1.ObservabilityConfigList, *observabilityconfigv1alpha1.ObservabilityConfigApplyConfiguration]
	Fake *FakeK8sV1alpha1
}

func newFakeObservabilityConfigs(fake *FakeK8sV1alpha1) typedobservabilityconfigv1alpha1.ObservabilityConfigInterface {
	return &fakeObservabilityConfigs{
		gentype.NewFakeClientWithListAndApply[*v1alpha1.ObservabilityConfig, *v1alpha1.ObservabilityConfigList, *observabilityconfigv1alpha1.ObservabilityConfigApplyConfiguration](
			fake.Fake,
			"",
			v1alpha1.SchemeGroupVersion.WithResource("observabilityconfigs"),
			v1alpha1.SchemeGroupVersion.WithKind("ObservabilityConfig"),
			func() *v1alpha1.ObservabilityConfig { return &v1alpha1.ObservabilityConfig{} },
			func() *v1alpha1.ObservabilityConfigList { return &v1alpha1.ObservabilityConfigList{} },
			func(dst, src *v1alpha1.ObservabilityConfigList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.ObservabilityConfigList) []*v1alpha1.ObservabilityConfig {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.ObservabilityConfigList, items []*v1alpha1.ObservabilityConfig) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
