// SPDX-FileCopyrightText: Copyright The OVN-Kubernetes Contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	egressfirewallv1 "github.com/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/crd/egressfirewall/v1"
	egressipv1 "github.com/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/crd/egressip/v1"
	apicorev1 "k8s.io/api/core/v1"
	corev1 "k8s.io/client-go/kubernetes/typed/core/v1"

	v1alpha1 "github.com/k8snetworkplumbingwg/ipamclaims/pkg/crd/ipamclaims/v1alpha1"
	v1 "github.com/openshift/api/cloudnetwork/v1"
	mock "github.com/stretchr/testify/mock"
)

// InterfaceOVN is an autogenerated mock type for the InterfaceOVN type
type InterfaceOVN struct {
	mock.Mock
}

// CreateCloudPrivateIPConfig provides a mock function with given fields: ctx, cloudPrivateIPConfig
func (_m *InterfaceOVN) CreateCloudPrivateIPConfig(ctx context.Context, cloudPrivateIPConfig *v1.CloudPrivateIPConfig) (*v1.CloudPrivateIPConfig, error) {
	ret := _m.Called(ctx, cloudPrivateIPConfig)

	if len(ret) == 0 {
		panic("no return value specified for CreateCloudPrivateIPConfig")
	}

	var r0 *v1.CloudPrivateIPConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.CloudPrivateIPConfig) (*v1.CloudPrivateIPConfig, error)); ok {
		return rf(ctx, cloudPrivateIPConfig)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.CloudPrivateIPConfig) *v1.CloudPrivateIPConfig); ok {
		r0 = rf(ctx, cloudPrivateIPConfig)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.CloudPrivateIPConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.CloudPrivateIPConfig) error); ok {
		r1 = rf(ctx, cloudPrivateIPConfig)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteCloudPrivateIPConfig provides a mock function with given fields: ctx, name
func (_m *InterfaceOVN) DeleteCloudPrivateIPConfig(ctx context.Context, name string) error {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCloudPrivateIPConfig")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Events provides a mock function with no fields
func (_m *InterfaceOVN) Events() corev1.EventInterface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Events")
	}

	var r0 corev1.EventInterface
	if rf, ok := ret.Get(0).(func() corev1.EventInterface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(corev1.EventInterface)
		}
	}

	return r0
}

// GetEgressFirewalls provides a mock function with no fields
func (_m *InterfaceOVN) GetEgressFirewalls() ([]*egressfirewallv1.EgressFirewall, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetEgressFirewalls")
	}

	var r0 []*egressfirewallv1.EgressFirewall
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*egressfirewallv1.EgressFirewall, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*egressfirewallv1.EgressFirewall); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*egressfirewallv1.EgressFirewall)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetEgressIP provides a mock function with given fields: name
func (_m *InterfaceOVN) GetEgressIP(name string) (*egressipv1.EgressIP, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for GetEgressIP")
	}

	var r0 *egressipv1.EgressIP
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*egressipv1.EgressIP, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) *egressipv1.EgressIP); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*egressipv1.EgressIP)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetEgressIPs provides a mock function with given fields: ctx
func (_m *InterfaceOVN) GetEgressIPs(ctx context.Context) ([]*egressipv1.EgressIP, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetEgressIPs")
	}

	var r0 []*egressipv1.EgressIP
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*egressipv1.EgressIP, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*egressipv1.EgressIP); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*egressipv1.EgressIP)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetNodeForWindows provides a mock function with given fields: name
func (_m *InterfaceOVN) GetNodeForWindows(name string) (*apicorev1.Node, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for GetNodeForWindows")
	}

	var r0 *apicorev1.Node
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*apicorev1.Node, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) *apicorev1.Node); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apicorev1.Node)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetNodesForWindows provides a mock function with no fields
func (_m *InterfaceOVN) GetNodesForWindows() ([]*apicorev1.Node, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetNodesForWindows")
	}

	var r0 []*apicorev1.Node
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*apicorev1.Node, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*apicorev1.Node); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*apicorev1.Node)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PatchEgressIP provides a mock function with given fields: ctx, name, patchData
func (_m *InterfaceOVN) PatchEgressIP(ctx context.Context, name string, patchData []byte) error {
	ret := _m.Called(ctx, name, patchData)

	if len(ret) == 0 {
		panic("no return value specified for PatchEgressIP")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte) error); ok {
		r0 = rf(ctx, name, patchData)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PatchNode provides a mock function with given fields: old, new
func (_m *InterfaceOVN) PatchNode(old *apicorev1.Node, new *apicorev1.Node) error {
	ret := _m.Called(old, new)

	if len(ret) == 0 {
		panic("no return value specified for PatchNode")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*apicorev1.Node, *apicorev1.Node) error); ok {
		r0 = rf(old, new)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PatchNodeStatus provides a mock function with given fields: old, new
func (_m *InterfaceOVN) PatchNodeStatus(old *apicorev1.Node, new *apicorev1.Node) error {
	ret := _m.Called(old, new)

	if len(ret) == 0 {
		panic("no return value specified for PatchNodeStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*apicorev1.Node, *apicorev1.Node) error); ok {
		r0 = rf(old, new)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PatchNodeStatusAnnotations provides a mock function with given fields: ctx, oldNode, newNode
func (_m *InterfaceOVN) PatchNodeStatusAnnotations(ctx context.Context, oldNode *apicorev1.Node, newNode *apicorev1.Node) error {
	ret := _m.Called(ctx, oldNode, newNode)

	if len(ret) == 0 {
		panic("no return value specified for PatchNodeStatusAnnotations")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *apicorev1.Node, *apicorev1.Node) error); ok {
		r0 = rf(ctx, oldNode, newNode)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PatchPodStatusAnnotations provides a mock function with given fields: ctx, oldPod, newPod
func (_m *InterfaceOVN) PatchPodStatusAnnotations(ctx context.Context, oldPod *apicorev1.Pod, newPod *apicorev1.Pod) error {
	ret := _m.Called(ctx, oldPod, newPod)

	if len(ret) == 0 {
		panic("no return value specified for PatchPodStatusAnnotations")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *apicorev1.Pod, *apicorev1.Pod) error); ok {
		r0 = rf(ctx, oldPod, newPod)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetAnnotationsOnNamespace provides a mock function with given fields: namespaceName, annotations
func (_m *InterfaceOVN) SetAnnotationsOnNamespace(namespaceName string, annotations map[string]interface{}) error {
	ret := _m.Called(namespaceName, annotations)

	if len(ret) == 0 {
		panic("no return value specified for SetAnnotationsOnNamespace")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, map[string]interface{}) error); ok {
		r0 = rf(namespaceName, annotations)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetAnnotationsOnNode provides a mock function with given fields: ctx, nodeName, annotations
func (_m *InterfaceOVN) SetAnnotationsOnNode(ctx context.Context, nodeName string, annotations map[string]interface{}) error {
	ret := _m.Called(ctx, nodeName, annotations)

	if len(ret) == 0 {
		panic("no return value specified for SetAnnotationsOnNode")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]interface{}) error); ok {
		r0 = rf(ctx, nodeName, annotations)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetAnnotationsOnNodeWithFieldManager provides a mock function with given fields: nodeName, annotations, fieldManager
func (_m *InterfaceOVN) SetAnnotationsOnNodeWithFieldManager(nodeName string, annotations map[string]interface{}, fieldManager string) error {
	ret := _m.Called(nodeName, annotations, fieldManager)

	if len(ret) == 0 {
		panic("no return value specified for SetAnnotationsOnNodeWithFieldManager")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, map[string]interface{}, string) error); ok {
		r0 = rf(nodeName, annotations, fieldManager)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetAnnotationsOnPod provides a mock function with given fields: namespace, podName, annotations
func (_m *InterfaceOVN) SetAnnotationsOnPod(namespace string, podName string, annotations map[string]interface{}) error {
	ret := _m.Called(namespace, podName, annotations)

	if len(ret) == 0 {
		panic("no return value specified for SetAnnotationsOnPod")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, map[string]interface{}) error); ok {
		r0 = rf(namespace, podName, annotations)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetAnnotationsOnService provides a mock function with given fields: namespace, serviceName, annotations
func (_m *InterfaceOVN) SetAnnotationsOnService(namespace string, serviceName string, annotations map[string]interface{}) error {
	ret := _m.Called(namespace, serviceName, annotations)

	if len(ret) == 0 {
		panic("no return value specified for SetAnnotationsOnService")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, map[string]interface{}) error); ok {
		r0 = rf(namespace, serviceName, annotations)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetLabelsOnNode provides a mock function with given fields: nodeName, labels
func (_m *InterfaceOVN) SetLabelsOnNode(nodeName string, labels map[string]interface{}) error {
	ret := _m.Called(nodeName, labels)

	if len(ret) == 0 {
		panic("no return value specified for SetLabelsOnNode")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, map[string]interface{}) error); ok {
		r0 = rf(nodeName, labels)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateCloudPrivateIPConfig provides a mock function with given fields: ctx, cloudPrivateIPConfig
func (_m *InterfaceOVN) UpdateCloudPrivateIPConfig(ctx context.Context, cloudPrivateIPConfig *v1.CloudPrivateIPConfig) (*v1.CloudPrivateIPConfig, error) {
	ret := _m.Called(ctx, cloudPrivateIPConfig)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCloudPrivateIPConfig")
	}

	var r0 *v1.CloudPrivateIPConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.CloudPrivateIPConfig) (*v1.CloudPrivateIPConfig, error)); ok {
		return rf(ctx, cloudPrivateIPConfig)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.CloudPrivateIPConfig) *v1.CloudPrivateIPConfig); ok {
		r0 = rf(ctx, cloudPrivateIPConfig)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.CloudPrivateIPConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.CloudPrivateIPConfig) error); ok {
		r1 = rf(ctx, cloudPrivateIPConfig)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateEgressFirewall provides a mock function with given fields: egressfirewall
func (_m *InterfaceOVN) UpdateEgressFirewall(egressfirewall *egressfirewallv1.EgressFirewall) error {
	ret := _m.Called(egressfirewall)

	if len(ret) == 0 {
		panic("no return value specified for UpdateEgressFirewall")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*egressfirewallv1.EgressFirewall) error); ok {
		r0 = rf(egressfirewall)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateEgressIP provides a mock function with given fields: eIP
func (_m *InterfaceOVN) UpdateEgressIP(eIP *egressipv1.EgressIP) error {
	ret := _m.Called(eIP)

	if len(ret) == 0 {
		panic("no return value specified for UpdateEgressIP")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*egressipv1.EgressIP) error); ok {
		r0 = rf(eIP)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateEgressServiceStatus provides a mock function with given fields: ctx, namespace, name, host
func (_m *InterfaceOVN) UpdateEgressServiceStatus(ctx context.Context, namespace string, name string, host string) error {
	ret := _m.Called(ctx, namespace, name, host)

	if len(ret) == 0 {
		panic("no return value specified for UpdateEgressServiceStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, namespace, name, host)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateIPAMClaimIPs provides a mock function with given fields: ctx, updatedIPAMClaim
func (_m *InterfaceOVN) UpdateIPAMClaimIPs(ctx context.Context, updatedIPAMClaim *v1alpha1.IPAMClaim) error {
	ret := _m.Called(ctx, updatedIPAMClaim)

	if len(ret) == 0 {
		panic("no return value specified for UpdateIPAMClaimIPs")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1alpha1.IPAMClaim) error); ok {
		r0 = rf(ctx, updatedIPAMClaim)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewInterfaceOVN creates a new instance of InterfaceOVN. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInterfaceOVN(t interface {
	mock.TestingT
	Cleanup(func())
}) *InterfaceOVN {
	mock := &InterfaceOVN{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
