/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	observabilityconfigv1alpha1 "github.com/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/crd/observabilityconfig/v1alpha1"
)

// FeatureConfigApplyConfiguration represents a declarative configuration of the FeatureConfig type for use
// with apply.
type FeatureConfigApplyConfiguration struct {
	Probability *int32                                            `json:"probability,omitempty"`
	Feature     *observabilityconfigv1alpha1.ObservabilityFeature `json:"feature,omitempty"`
}

// FeatureConfigApplyConfiguration constructs a declarative configuration of the FeatureConfig type for use with
// apply.
func FeatureConfig() *FeatureConfigApplyConfiguration {
	return &FeatureConfigApplyConfiguration{}
}

// WithProbability sets the Probability field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Probability field is set to the value of the last call.
func (b *FeatureConfigApplyConfiguration) WithProbability(value int32) *FeatureConfigApplyConfiguration {
	b.Probability = &value
	return b
}

// WithFeature sets the Feature field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Feature field is set to the value of the last call.
func (b *FeatureConfigApplyConfiguration) WithFeature(value observabilityconfigv1alpha1.ObservabilityFeature) *FeatureConfigApplyConfiguration {
	b.Feature = &value
	return b
}
