// SPDX-FileCopyrightText: Copyright The OVN-Kubernetes Contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	observabilityconfigv1alpha1 "github.com/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/crd/observabilityconfig/v1alpha1"
)

// FeatureConfigApplyConfiguration represents a declarative configuration of the FeatureConfig type for use
// with apply.
type FeatureConfigApplyConfiguration struct {
	// Probability is the probability of the feature being sampled in percent.
	Probability *int32 `json:"probability,omitempty"`
	// Feature is the Observability feature that should be sampled.
	Feature *observabilityconfigv1alpha1.ObservabilityFeature `json:"feature,omitempty"`
}

// FeatureConfigApplyConfiguration constructs a declarative configuration of the FeatureConfig type for use with
// apply.
func FeatureConfig() *FeatureConfigApplyConfiguration {
	return &FeatureConfigApplyConfiguration{}
}

// WithProbability sets the Probability field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Probability field is set to the value of the last call.
func (b *FeatureConfigApplyConfiguration) WithProbability(value int32) *FeatureConfigApplyConfiguration {
	b.Probability = &value
	return b
}

// WithFeature sets the Feature field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Feature field is set to the value of the last call.
func (b *FeatureConfigApplyConfiguration) WithFeature(value observabilityconfigv1alpha1.ObservabilityFeature) *FeatureConfigApplyConfiguration {
	b.Feature = &value
	return b
}
