// SPDX-FileCopyrightText: Copyright The OVN-Kubernetes Contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// FilterApplyConfiguration represents a declarative configuration of the Filter type for use
// with apply.
//
// Filter allows to apply ObservabilityConfig in a granular manner.
// Currently, it supports node and namespace based filtering.
// If both node and namespace filters are specifies, they are logically ANDed.
type FilterApplyConfiguration struct {
	// nodeSelector applies ObservabilityConfig only to nodes that match the selector.
	NodeSelector *v1.LabelSelectorApplyConfiguration `json:"nodeSelector,omitempty"`
	// namespaces is a list of namespaces to which the ObservabilityConfig should be applied.
	// It only applies to the namespaced features, currently that includes NetworkPolicy and EgressFirewall.
	Namespaces *[]string `json:"namespaces,omitempty"`
}

// FilterApplyConfiguration constructs a declarative configuration of the Filter type for use with
// apply.
func Filter() *FilterApplyConfiguration {
	return &FilterApplyConfiguration{}
}

// WithNodeSelector sets the NodeSelector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NodeSelector field is set to the value of the last call.
func (b *FilterApplyConfiguration) WithNodeSelector(value *v1.LabelSelectorApplyConfiguration) *FilterApplyConfiguration {
	b.NodeSelector = value
	return b
}

// WithNamespaces sets the Namespaces field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespaces field is set to the value of the last call.
func (b *FilterApplyConfiguration) WithNamespaces(value []string) *FilterApplyConfiguration {
	b.Namespaces = &value
	return b
}
