// SPDX-FileCopyrightText: Copyright The OVN-Kubernetes Contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// ObservabilitySpecApplyConfiguration represents a declarative configuration of the ObservabilitySpec type for use
// with apply.
type ObservabilitySpecApplyConfiguration struct {
	// CollectorID is the OVN Sample_Collector set_id: unique across the cluster, range 1 to 4,294,967,295 (MaxUint32).
	CollectorID *int64 `json:"collectorID,omitempty"`
	// Features is a list of Observability features that can generate samples and their probabilities for a given collector.
	Features []FeatureConfigApplyConfiguration `json:"features,omitempty"`
	// Filter allows to apply ObservabilityConfig in a granular manner.
	Filter *FilterApplyConfiguration `json:"filter,omitempty"`
}

// ObservabilitySpecApplyConfiguration constructs a declarative configuration of the ObservabilitySpec type for use with
// apply.
func ObservabilitySpec() *ObservabilitySpecApplyConfiguration {
	return &ObservabilitySpecApplyConfiguration{}
}

// WithCollectorID sets the CollectorID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CollectorID field is set to the value of the last call.
func (b *ObservabilitySpecApplyConfiguration) WithCollectorID(value int64) *ObservabilitySpecApplyConfiguration {
	b.CollectorID = &value
	return b
}

// WithFeatures adds the given value to the Features field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Features field.
func (b *ObservabilitySpecApplyConfiguration) WithFeatures(values ...*FeatureConfigApplyConfiguration) *ObservabilitySpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithFeatures")
		}
		b.Features = append(b.Features, *values[i])
	}
	return b
}

// WithFilter sets the Filter field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Filter field is set to the value of the last call.
func (b *ObservabilitySpecApplyConfiguration) WithFilter(value *FilterApplyConfiguration) *ObservabilitySpecApplyConfiguration {
	b.Filter = value
	return b
}
