/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// ObservabilitySpecApplyConfiguration represents a declarative configuration of the ObservabilitySpec type for use
// with apply.
type ObservabilitySpecApplyConfiguration struct {
	CollectorID *int64                            `json:"collectorID,omitempty"`
	Features    []FeatureConfigApplyConfiguration `json:"features,omitempty"`
	Filter      *FilterApplyConfiguration         `json:"filter,omitempty"`
}

// ObservabilitySpecApplyConfiguration constructs a declarative configuration of the ObservabilitySpec type for use with
// apply.
func ObservabilitySpec() *ObservabilitySpecApplyConfiguration {
	return &ObservabilitySpecApplyConfiguration{}
}

// WithCollectorID sets the CollectorID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CollectorID field is set to the value of the last call.
func (b *ObservabilitySpecApplyConfiguration) WithCollectorID(value int64) *ObservabilitySpecApplyConfiguration {
	b.CollectorID = &value
	return b
}

// WithFeatures adds the given value to the Features field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Features field.
func (b *ObservabilitySpecApplyConfiguration) WithFeatures(values ...*FeatureConfigApplyConfiguration) *ObservabilitySpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithFeatures")
		}
		b.Features = append(b.Features, *values[i])
	}
	return b
}

// WithFilter sets the Filter field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Filter field is set to the value of the last call.
func (b *ObservabilitySpecApplyConfiguration) WithFilter(value *FilterApplyConfiguration) *ObservabilitySpecApplyConfiguration {
	b.Filter = value
	return b
}
