// SPDX-FileCopyrightText: Copyright The OVN-Kubernetes Contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// ObservabilityConfigListerExpansion allows custom methods to be added to
// ObservabilityConfigLister.
type ObservabilityConfigListerExpansion interface{}

// ObservabilityConfigNamespaceListerExpansion allows custom methods to be added to
// ObservabilityConfigNamespaceLister.
type ObservabilityConfigNamespaceListerExpansion interface{}
