// SPDX-FileCopyrightText: Copyright The OVN-Kubernetes Contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	observabilityconfigv1alpha1 "github.com/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/crd/observabilityconfig/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// ObservabilityConfigLister helps list ObservabilityConfigs.
// All objects returned here must be treated as read-only.
type ObservabilityConfigLister interface {
	// List lists all ObservabilityConfigs in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*observabilityconfigv1alpha1.ObservabilityConfig, err error)
	// Get retrieves the ObservabilityConfig from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*observabilityconfigv1alpha1.ObservabilityConfig, error)
	ObservabilityConfigListerExpansion
}

// observabilityConfigLister implements the ObservabilityConfigLister interface.
type observabilityConfigLister struct {
	listers.ResourceIndexer[*observabilityconfigv1alpha1.ObservabilityConfig]
}

// NewObservabilityConfigLister returns a new ObservabilityConfigLister.
func NewObservabilityConfigLister(indexer cache.Indexer) ObservabilityConfigLister {
	return &observabilityConfigLister{listers.New[*observabilityconfigv1alpha1.ObservabilityConfig](indexer, observabilityconfigv1alpha1.Resource("observabilityconfig"))}
}
