/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// VTEPAllocationApplyConfiguration represents a declarative configuration of the VTEPAllocation type for use
// with apply.
type VTEPAllocationApplyConfiguration struct {
	Node *string `json:"node,omitempty"`
	IP   *string `json:"ip,omitempty"`
}

// VTEPAllocationApplyConfiguration constructs a declarative configuration of the VTEPAllocation type for use with
// apply.
func VTEPAllocation() *VTEPAllocationApplyConfiguration {
	return &VTEPAllocationApplyConfiguration{}
}

// WithNode sets the Node field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Node field is set to the value of the last call.
func (b *VTEPAllocationApplyConfiguration) WithNode(value string) *VTEPAllocationApplyConfiguration {
	b.Node = &value
	return b
}

// WithIP sets the IP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IP field is set to the value of the last call.
func (b *VTEPAllocationApplyConfiguration) WithIP(value string) *VTEPAllocationApplyConfiguration {
	b.IP = &value
	return b
}
