/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	egressiptrafficv1 "github.com/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/crd/egressiptraffic/v1"
	applyconfigurationegressiptrafficv1 "github.com/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/crd/egressiptraffic/v1/apis/applyconfiguration/egressiptraffic/v1"
	scheme "github.com/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/crd/egressiptraffic/v1/apis/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// EgressIPTrafficsGetter has a method to return a EgressIPTrafficInterface.
// A group's client should implement this interface.
type EgressIPTrafficsGetter interface {
	EgressIPTraffics() EgressIPTrafficInterface
}

// EgressIPTrafficInterface has methods to work with EgressIPTraffic resources.
type EgressIPTrafficInterface interface {
	Create(ctx context.Context, egressIPTraffic *egressiptrafficv1.EgressIPTraffic, opts metav1.CreateOptions) (*egressiptrafficv1.EgressIPTraffic, error)
	Update(ctx context.Context, egressIPTraffic *egressiptrafficv1.EgressIPTraffic, opts metav1.UpdateOptions) (*egressiptrafficv1.EgressIPTraffic, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*egressiptrafficv1.EgressIPTraffic, error)
	List(ctx context.Context, opts metav1.ListOptions) (*egressiptrafficv1.EgressIPTrafficList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *egressiptrafficv1.EgressIPTraffic, err error)
	Apply(ctx context.Context, egressIPTraffic *applyconfigurationegressiptrafficv1.EgressIPTrafficApplyConfiguration, opts metav1.ApplyOptions) (result *egressiptrafficv1.EgressIPTraffic, err error)
	EgressIPTrafficExpansion
}

// egressIPTraffics implements EgressIPTrafficInterface
type egressIPTraffics struct {
	*gentype.ClientWithListAndApply[*egressiptrafficv1.EgressIPTraffic, *egressiptrafficv1.EgressIPTrafficList, *applyconfigurationegressiptrafficv1.EgressIPTrafficApplyConfiguration]
}

// newEgressIPTraffics returns a EgressIPTraffics
func newEgressIPTraffics(c *K8sV1Client) *egressIPTraffics {
	return &egressIPTraffics{
		gentype.NewClientWithListAndApply[*egressiptrafficv1.EgressIPTraffic, *egressiptrafficv1.EgressIPTrafficList, *applyconfigurationegressiptrafficv1.EgressIPTrafficApplyConfiguration](
			"egressiptraffics",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *egressiptrafficv1.EgressIPTraffic { return &egressiptrafficv1.EgressIPTraffic{} },
			func() *egressiptrafficv1.EgressIPTrafficList { return &egressiptrafficv1.EgressIPTrafficList{} },
		),
	}
}
