// SPDX-FileCopyrightText: Copyright The OVN-Kubernetes Contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package applyconfiguration

import (
	v1alpha1 "github.com/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/crd/observabilityconfig/v1alpha1"
	internal "github.com/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/crd/observabilityconfig/v1alpha1/apis/applyconfiguration/internal"
	observabilityconfigv1alpha1 "github.com/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/crd/observabilityconfig/v1alpha1/apis/applyconfiguration/observabilityconfig/v1alpha1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	managedfields "k8s.io/apimachinery/pkg/util/managedfields"
)

// ForKind returns an apply configuration type for the given GroupVersionKind, or nil if no
// apply configuration type exists for the given GroupVersionKind.
func ForKind(kind schema.GroupVersionKind) interface{} {
	switch kind {
	// Group=k8s.ovn.org, Version=v1alpha1
	case v1alpha1.SchemeGroupVersion.WithKind("FeatureConfig"):
		return &observabilityconfigv1alpha1.FeatureConfigApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("Filter"):
		return &observabilityconfigv1alpha1.FilterApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ObservabilityConfig"):
		return &observabilityconfigv1alpha1.ObservabilityConfigApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ObservabilitySpec"):
		return &observabilityconfigv1alpha1.ObservabilitySpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ObservabilityStatus"):
		return &observabilityconfigv1alpha1.ObservabilityStatusApplyConfiguration{}

	}
	return nil
}

func NewTypeConverter(scheme *runtime.Scheme) managedfields.TypeConverter {
	return managedfields.NewSchemeTypeConverter(scheme, internal.Parser())
}
