/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	context "context"
	time "time"

	crdvirtualprivatenetworkconnectv1 "github.com/ovn-org/ovn-kubernetes/go-controller/pkg/crd/virtualprivatenetworkconnect/v1"
	versioned "github.com/ovn-org/ovn-kubernetes/go-controller/pkg/crd/virtualprivatenetworkconnect/v1/apis/clientset/versioned"
	internalinterfaces "github.com/ovn-org/ovn-kubernetes/go-controller/pkg/crd/virtualprivatenetworkconnect/v1/apis/informers/externalversions/internalinterfaces"
	virtualprivatenetworkconnectv1 "github.com/ovn-org/ovn-kubernetes/go-controller/pkg/crd/virtualprivatenetworkconnect/v1/apis/listers/virtualprivatenetworkconnect/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// VirtualPrivateNetworkConnectInformer provides access to a shared informer and lister for
// VirtualPrivateNetworkConnects.
type VirtualPrivateNetworkConnectInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() virtualprivatenetworkconnectv1.VirtualPrivateNetworkConnectLister
}

type virtualPrivateNetworkConnectInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewVirtualPrivateNetworkConnectInformer constructs a new informer for VirtualPrivateNetworkConnect type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewVirtualPrivateNetworkConnectInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredVirtualPrivateNetworkConnectInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredVirtualPrivateNetworkConnectInformer constructs a new informer for VirtualPrivateNetworkConnect type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredVirtualPrivateNetworkConnectInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.K8sV1().VirtualPrivateNetworkConnects().List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.K8sV1().VirtualPrivateNetworkConnects().Watch(context.TODO(), options)
			},
		},
		&crdvirtualprivatenetworkconnectv1.VirtualPrivateNetworkConnect{},
		resyncPeriod,
		indexers,
	)
}

func (f *virtualPrivateNetworkConnectInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredVirtualPrivateNetworkConnectInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *virtualPrivateNetworkConnectInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&crdvirtualprivatenetworkconnectv1.VirtualPrivateNetworkConnect{}, f.defaultInformer)
}

func (f *virtualPrivateNetworkConnectInformer) Lister() virtualprivatenetworkconnectv1.VirtualPrivateNetworkConnectLister {
	return virtualprivatenetworkconnectv1.NewVirtualPrivateNetworkConnectLister(f.Informer().GetIndexer())
}
