/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// EVPNConfigurationApplyConfiguration represents a declarative configuration of the EVPNConfiguration type for use
// with apply.
type EVPNConfigurationApplyConfiguration struct {
	VTEP   *string                      `json:"vtep,omitempty"`
	MACVRF *VRFConfigApplyConfiguration `json:"macVRF,omitempty"`
	IPVRF  *VRFConfigApplyConfiguration `json:"ipVRF,omitempty"`
}

// EVPNConfigurationApplyConfiguration constructs a declarative configuration of the EVPNConfiguration type for use with
// apply.
func EVPNConfiguration() *EVPNConfigurationApplyConfiguration {
	return &EVPNConfigurationApplyConfiguration{}
}

// WithVTEP sets the VTEP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VTEP field is set to the value of the last call.
func (b *EVPNConfigurationApplyConfiguration) WithVTEP(value string) *EVPNConfigurationApplyConfiguration {
	b.VTEP = &value
	return b
}

// WithMACVRF sets the MACVRF field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MACVRF field is set to the value of the last call.
func (b *EVPNConfigurationApplyConfiguration) WithMACVRF(value *VRFConfigApplyConfiguration) *EVPNConfigurationApplyConfiguration {
	b.MACVRF = value
	return b
}

// WithIPVRF sets the IPVRF field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IPVRF field is set to the value of the last call.
func (b *EVPNConfigurationApplyConfiguration) WithIPVRF(value *VRFConfigApplyConfiguration) *EVPNConfigurationApplyConfiguration {
	b.IPVRF = value
	return b
}
