mode: daemonset
image:
  repository: otel/opentelemetry-collector-k8s
hostNetwork: true
dnsPolicy: ClusterFirstWithHostNet
config:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
  processors:
    batch: {}
  exporters:
    otlp:
      endpoint: tempo.tracing.svc.cluster.local:4317
      tls:
        insecure: true
  service:
    pipelines:
      traces:
        receivers: [otlp]
        processors: [batch]
        exporters: [otlp]
