// SPDX-FileCopyrightText: Copyright The OVN-Kubernetes Contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	observabilityconfigv1alpha1 "github.com/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/crd/observabilityconfig/v1alpha1"
	applyconfigurationobservabilityconfigv1alpha1 "github.com/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/crd/observabilityconfig/v1alpha1/apis/applyconfiguration/observabilityconfig/v1alpha1"
	scheme "github.com/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/crd/observabilityconfig/v1alpha1/apis/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ObservabilityConfigsGetter has a method to return a ObservabilityConfigInterface.
// A group's client should implement this interface.
type ObservabilityConfigsGetter interface {
	ObservabilityConfigs(namespace string) ObservabilityConfigInterface
}

// ObservabilityConfigInterface has methods to work with ObservabilityConfig resources.
type ObservabilityConfigInterface interface {
	Create(ctx context.Context, observabilityConfig *observabilityconfigv1alpha1.ObservabilityConfig, opts v1.CreateOptions) (*observabilityconfigv1alpha1.ObservabilityConfig, error)
	Update(ctx context.Context, observabilityConfig *observabilityconfigv1alpha1.ObservabilityConfig, opts v1.UpdateOptions) (*observabilityconfigv1alpha1.ObservabilityConfig, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, observabilityConfig *observabilityconfigv1alpha1.ObservabilityConfig, opts v1.UpdateOptions) (*observabilityconfigv1alpha1.ObservabilityConfig, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*observabilityconfigv1alpha1.ObservabilityConfig, error)
	List(ctx context.Context, opts v1.ListOptions) (*observabilityconfigv1alpha1.ObservabilityConfigList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *observabilityconfigv1alpha1.ObservabilityConfig, err error)
	Apply(ctx context.Context, observabilityConfig *applyconfigurationobservabilityconfigv1alpha1.ObservabilityConfigApplyConfiguration, opts v1.ApplyOptions) (result *observabilityconfigv1alpha1.ObservabilityConfig, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, observabilityConfig *applyconfigurationobservabilityconfigv1alpha1.ObservabilityConfigApplyConfiguration, opts v1.ApplyOptions) (result *observabilityconfigv1alpha1.ObservabilityConfig, err error)
	ObservabilityConfigExpansion
}

// observabilityConfigs implements ObservabilityConfigInterface
type observabilityConfigs struct {
	*gentype.ClientWithListAndApply[*observabilityconfigv1alpha1.ObservabilityConfig, *observabilityconfigv1alpha1.ObservabilityConfigList, *applyconfigurationobservabilityconfigv1alpha1.ObservabilityConfigApplyConfiguration]
}

// newObservabilityConfigs returns a ObservabilityConfigs
func newObservabilityConfigs(c *K8sV1alpha1Client, namespace string) *observabilityConfigs {
	return &observabilityConfigs{
		gentype.NewClientWithListAndApply[*observabilityconfigv1alpha1.ObservabilityConfig, *observabilityconfigv1alpha1.ObservabilityConfigList, *applyconfigurationobservabilityconfigv1alpha1.ObservabilityConfigApplyConfiguration](
			"observabilityconfigs",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *observabilityconfigv1alpha1.ObservabilityConfig {
				return &observabilityconfigv1alpha1.ObservabilityConfig{}
			},
			func() *observabilityconfigv1alpha1.ObservabilityConfigList {
				return &observabilityconfigv1alpha1.ObservabilityConfigList{}
			},
		),
	}
}
